### ISSUE TITLE
Error with using add_unique() with loans

### ISSUE THREAD

**Issue by masasin** [MartinPyka/financial_life#9]
When adding a unique from loan to a dummy account:

    simulation.add_unique(loan, 'Damages', 12000, date=datetime(2020,1,1))

I get the following error:

```
/home/masasin/.virtualenvs/financial_life/lib/python3.6/site-packages/financial_life/financing/accounts.py:706: UserWarning: Difference between current date and next date is 0 and not 1
  warnings.warn('Difference between current date and next date is %i and not 1' % delta)
Traceback (most recent call last):
  File "finsim.py", line 19, in <module>
    simulation.simulate(delta=timedelta(days=365*10))
  File "/home/masasin/.virtualenvs/financial_life/lib/python3.6/site-packages/financial_life/financing/accounts.py", line 509, in simulate
    self.make_transfer(payment)
  File "/home/masasin/.virtualenvs/financial_life/lib/python3.6/site-packages/financial_life/financing/accounts.py", line 462, in make_transfer
    meta = payment['meta']
TypeError: make_report() got an unexpected keyword argument 'date'
```

You can simulate the expected behaviour by doing:

    simulation.add_unique('Damages', loan, -12000, date=datetime(2020,1,1))

edit: This doesn't do anything either if the starting loan amount is 0, but works when it is 0.01 or any other number.

**Comment by MartinPyka** [comment]
thanks for the bug-report. in general, transfering something from a loan to another account is not allowed. But the method, that handles this, had an error. I fixed it in https://github.com/MartinPyka/financial_life/commit/7937b5423d541e6f59b76ed4b12bdae1a262cd06
